Avoid Lucene index input to be opened with READONCE context on indexing shards (#2881)
Since apache/lucene#13535, memory-maped Lucene index inputs 
opened with a IOContext.READONCE are expected to be closed by 
the same thread that opened the input, otherwise the following 
assertion can trip:

java.lang.WrongThreadException: Attempted access outside owning thread

This is not the case for ReopeningIndexInput which can be closed 
(and therefore close the underlying input) by the thread that uploaded 
the file to the object store.

Closes #2877
Closes #2876
Closes #2882
Closes #2880