Revert "Mute co.elastic.elasticsearch.serverless.datastream.ServerlessDataStreamLifecycleIT testILMPolicesAreNotInstalled #2841" (#2846)
In #2841 the test fails because it cannot load a settings template.
Looking at the logs it appears there was an issue with the index mode
used in the template:

```
[2024-09-26T09:00:37,282][ERROR][o.e.x.c.t.IndexTemplateRegistry] [index-OtipeBO] error adding index template [logs@settings] for [stack]
java.lang.IllegalArgumentException: No enum constant org.elasticsearch.index.IndexMode.${XPACK.STACK.TEMPLATE.LOGSDB.INDEX.MODE}
	at java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
	at org.elasticsearch.common.settings.Setting.lambda$enumSetting$16(Setting.java:1619) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.settings.Setting.get(Setting.java:536) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
```

PR https://github.com/elastic/elasticsearch-serverless/pull/2845 fixed
that so we revert PR that muted the tests.

Fixes: https://github.com/elastic/elasticsearch-serverless/issues/2841